package Form;
import LoginAdmin.login;
import LoginAdmin.login;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Panel;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naufal Sholahuddin
 */
public class MenuUtama extends javax.swing.JFrame {
    
    /**
     * Creates new form menu
     */
    Timer timer;
    Color hoverButton;
    private Connection conn = new koneksi().connect();
    private String pilihNis;
    private String pilihSemester;
    private String keterangan;
    
    public MenuUtama() {
        initComponents();
        setVisible(true);
        
        sliderMenuDefault();
        
        JamTanggal();
        this.hoverButton = form.getBackground();
       
        getRelasiNisTengahSm();
        getRelasiNisAkhirSm();
    }
    
    // untuk sliderMenu
    private void sliderMenuDefault(){
        slideMenuForm.setVisible(false);
        slideMenuTransaksi.setVisible(false);
        slideMenuLaporan.setVisible(false);
    }
    
    private void hiddenSubMenu(){
        if(slideMenuForm.isVisible() == true){
            slideMenuForm.setVisible(false);
        }
        if(slideMenuTransaksi.isVisible() == true){
            slideMenuTransaksi.setVisible(false);
        }
        if(slideMenuLaporan.isVisible() == true){
            slideMenuLaporan.setVisible(false);
        }
    }
    
    private void showSubMenu(JPanel subMenu){
        if(subMenu.isVisible() == false){
            hiddenSubMenu();
            subMenu.setVisible(true);
        }else{
            subMenu.setVisible(false);
        }
    }
    //akhis slider menu
    
    //clock
    private void JamTanggal(){
        ActionListener actionListener = new ActionListener(){
           @Override
            public void actionPerformed(ActionEvent e) {
                //Time in 24Hrs Format
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
                String time = timeFormat.format(date);
                clock.setText(time);
                //Todays Date
                Date date2 = new Date();
                DateFormat timeFormat2 = new SimpleDateFormat("dd/MM/yyyy");
                String time2 = timeFormat2.format(date2);
                tanggal.setText(time2);
           }     
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        cbPilihNisTengahSm = new javax.swing.JComboBox<>();
        cbPilihNisAkhirSm = new javax.swing.JComboBox<>();
        cbPilihSemester = new javax.swing.JComboBox<>();
        PanelDashboard = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        penilaian = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        slideMenuForm = new javax.swing.JPanel();
        menuGuru = new javax.swing.JLabel();
        menuSiswa = new javax.swing.JLabel();
        menuPelajaran = new javax.swing.JLabel();
        menuAbsen = new javax.swing.JLabel();
        menuWaliKelas = new javax.swing.JLabel();
        slideMenuTransaksi = new javax.swing.JPanel();
        menuNilai = new javax.swing.JLabel();
        slideMenuLaporan = new javax.swing.JPanel();
        menuReportGuru = new javax.swing.JLabel();
        menuReportSiswa = new javax.swing.JLabel();
        menuReportWaliKelas = new javax.swing.JLabel();
        menuReportRaportSiswaTengahSemester = new javax.swing.JLabel();
        menuReportRaportSiswaAkhirSemester = new javax.swing.JLabel();
        form = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        MenuLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        Pane = new javax.swing.JPanel();
        Panel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        clock = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        cbPilihNisTengahSm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih NIS" }));

        cbPilihNisAkhirSm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih NIS" }));

        cbPilihSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GANJIL", "GENAP" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 620));
        setSize(new java.awt.Dimension(0, 0));

        PanelDashboard.setBackground(new java.awt.Color(0, 153, 204));
        PanelDashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(255, 255, 255)));
        PanelDashboard.setMaximumSize(new java.awt.Dimension(1500, 700));
        PanelDashboard.setMinimumSize(new java.awt.Dimension(950, 520));
        PanelDashboard.setPreferredSize(new java.awt.Dimension(1100, 590));

        Menu.setBackground(new java.awt.Color(0, 102, 153));
        Menu.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        Menu.setMaximumSize(new java.awt.Dimension(32767, 600));

        Panel2.setBackground(new java.awt.Color(0, 102, 153));
        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dashboard.setBackground(new java.awt.Color(0, 102, 153));
        dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("  Dashboard");
        dashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dashboard.setOpaque(true);
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });

        penilaian.setBackground(new java.awt.Color(0, 102, 153));
        penilaian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        penilaian.setForeground(new java.awt.Color(255, 255, 255));
        penilaian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penilaian.setText("Penilaian");
        penilaian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        penilaian.setOpaque(true);
        penilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penilaianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penilaianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penilaianMouseExited(evt);
            }
        });

        laporan.setBackground(new java.awt.Color(0, 102, 153));
        laporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporan.setText("  Laporan");
        laporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        laporan.setOpaque(true);
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        slideMenuForm.setBackground(new java.awt.Color(255, 255, 255));

        menuGuru.setBackground(new java.awt.Color(255, 255, 255));
        menuGuru.setText("       Guru");
        menuGuru.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuGuru.setOpaque(true);
        menuGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuGuruMouseExited(evt);
            }
        });

        menuSiswa.setBackground(new java.awt.Color(255, 255, 255));
        menuSiswa.setText("       Siswa");
        menuSiswa.setOpaque(true);
        menuSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuSiswaMouseExited(evt);
            }
        });

        menuPelajaran.setBackground(new java.awt.Color(255, 255, 255));
        menuPelajaran.setText("       Pelajaran");
        menuPelajaran.setOpaque(true);
        menuPelajaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPelajaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPelajaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPelajaranMouseExited(evt);
            }
        });

        menuAbsen.setBackground(new java.awt.Color(255, 255, 255));
        menuAbsen.setText("       Absen");
        menuAbsen.setOpaque(true);
        menuAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAbsenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAbsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAbsenMouseExited(evt);
            }
        });

        menuWaliKelas.setBackground(new java.awt.Color(255, 255, 255));
        menuWaliKelas.setText("       Wali Kelas");
        menuWaliKelas.setOpaque(true);
        menuWaliKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuWaliKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuWaliKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuWaliKelasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuFormLayout = new javax.swing.GroupLayout(slideMenuForm);
        slideMenuForm.setLayout(slideMenuFormLayout);
        slideMenuFormLayout.setHorizontalGroup(
            slideMenuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuWaliKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuFormLayout.setVerticalGroup(
            slideMenuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuFormLayout.createSequentialGroup()
                .addComponent(menuGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuWaliKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        slideMenuTransaksi.setBackground(new java.awt.Color(255, 255, 255));

        menuNilai.setBackground(new java.awt.Color(255, 255, 255));
        menuNilai.setText("       Nilai");
        menuNilai.setOpaque(true);
        menuNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNilaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuNilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuNilaiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuTransaksiLayout = new javax.swing.GroupLayout(slideMenuTransaksi);
        slideMenuTransaksi.setLayout(slideMenuTransaksiLayout);
        slideMenuTransaksiLayout.setHorizontalGroup(
            slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );
        slideMenuTransaksiLayout.setVerticalGroup(
            slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(slideMenuTransaksiLayout.createSequentialGroup()
                    .addComponent(menuNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        slideMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));

        menuReportGuru.setBackground(new java.awt.Color(255, 255, 255));
        menuReportGuru.setText("       Laporan Data Guru");
        menuReportGuru.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportGuru.setOpaque(true);
        menuReportGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportGuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportGuruMouseExited(evt);
            }
        });

        menuReportSiswa.setBackground(new java.awt.Color(255, 255, 255));
        menuReportSiswa.setText("       Laporan Data Siswa");
        menuReportSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportSiswa.setOpaque(true);
        menuReportSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportSiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportSiswaMouseExited(evt);
            }
        });

        menuReportWaliKelas.setBackground(new java.awt.Color(255, 255, 255));
        menuReportWaliKelas.setText("       Laporan Data Wali Kelas");
        menuReportWaliKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportWaliKelas.setOpaque(true);
        menuReportWaliKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportWaliKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportWaliKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportWaliKelasMouseExited(evt);
            }
        });

        menuReportRaportSiswaTengahSemester.setBackground(new java.awt.Color(255, 255, 255));
        menuReportRaportSiswaTengahSemester.setText("       Raport Siswa Tengah Semester");
        menuReportRaportSiswaTengahSemester.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportRaportSiswaTengahSemester.setOpaque(true);
        menuReportRaportSiswaTengahSemester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportRaportSiswaTengahSemesterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportRaportSiswaTengahSemesterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportRaportSiswaTengahSemesterMouseExited(evt);
            }
        });

        menuReportRaportSiswaAkhirSemester.setBackground(new java.awt.Color(255, 255, 255));
        menuReportRaportSiswaAkhirSemester.setText("       Raport Siswa Akhir Semester");
        menuReportRaportSiswaAkhirSemester.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportRaportSiswaAkhirSemester.setOpaque(true);
        menuReportRaportSiswaAkhirSemester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportRaportSiswaAkhirSemesterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportRaportSiswaAkhirSemesterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportRaportSiswaAkhirSemesterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuLaporanLayout = new javax.swing.GroupLayout(slideMenuLaporan);
        slideMenuLaporan.setLayout(slideMenuLaporanLayout);
        slideMenuLaporanLayout.setHorizontalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuReportGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportWaliKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportRaportSiswaTengahSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportRaportSiswaAkhirSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuLaporanLayout.setVerticalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuLaporanLayout.createSequentialGroup()
                .addComponent(menuReportGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportRaportSiswaTengahSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportRaportSiswaAkhirSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        form.setBackground(new java.awt.Color(0, 102, 153));
        form.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        form.setForeground(new java.awt.Color(255, 255, 255));
        form.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        form.setText("  Form");
        form.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        form.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        form.setOpaque(true);
        form.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(penilaian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penilaian, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("  Log Out");
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuLogo.setBackground(new java.awt.Color(0, 102, 153));
        MenuLogo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        logo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo1.png"))); // NOI18N

        judul1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setText("Sistem Akademik");

        judul2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setText("SMPIT MAULANA ABBASYIAH");

        javax.swing.GroupLayout MenuLogoLayout = new javax.swing.GroupLayout(MenuLogo);
        MenuLogo.setLayout(MenuLogoLayout);
        MenuLogoLayout.setHorizontalGroup(
            MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLogoLayout.createSequentialGroup()
                .addGroup(MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLogoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(judul1)
                            .addComponent(logo)))
                    .addGroup(MenuLogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(judul2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLogoLayout.setVerticalGroup(
            MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLogoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judul1)
                .addGap(11, 11, 11)
                .addComponent(judul2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pane.setBackground(new java.awt.Color(255, 255, 255));
        Pane.setMaximumSize(new java.awt.Dimension(1200, 650));
        Pane.setMinimumSize(new java.awt.Dimension(380, 200));
        Pane.setPreferredSize(new java.awt.Dimension(600, 570));
        Pane.setLayout(new java.awt.CardLayout());

        Panel3.setBackground(new java.awt.Color(255, 255, 255));
        Panel3.setMinimumSize(new java.awt.Dimension(950, 650));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("  Dashboard");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(51, 51, 51)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 153, 204)));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/img2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("SMPIT MAULANA ABBASYIAH");

        jLabel2.setText("Kp. Palabali No. 82-B RT 011/06, Bojong Pondok Terong, Kec. Cipayung, Kota Depok, Prov. Jawa Barat");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 153, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clock.setForeground(new java.awt.Color(255, 255, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 44));

        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 116, 44));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/clockz.jpg"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 153, 204)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Detail Sekolah");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel41.setText("Kepala Sekolah              :  Nurhadi, S. Pd.");

        jLabel40.setText("Akreditasi : - ");

        jLabel42.setText("Operator                       :  Qorry Widya Astuti");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("NSS/NDS/NIS/NPSN : 70015011");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("Izin Operasional       : 421.3/0123/DPMPTSP/XI/2021");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel40)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46))
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addGap(21, 21, 21)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 153, 204)));

        jLabel4.setText("Guru : 8");

        jLabel5.setText("Siswa Laki - laki : 28");

        jLabel6.setText("Siswa Perempuan : 18");

        jLabel7.setText("Rombongan Belajar : 3");

        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Kurikulum : SMP 2013");

        jLabel11.setText("Penyelengaraan : Sehari Penuh/5 hari");

        jLabel12.setText("Manajemen Berbasis Sekolah : Ya");

        jLabel13.setText("Semester Data : 2021/2022-2");

        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel30.setText("Sumber Listrik : PLN");

        jLabel31.setText("Akses Internet : Smartfren");

        jLabel32.setText("Daya Listrik : 6,000");

        jLabel33.setText("Luas Tanah : 1,250M²");

        jLabel34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel35.setText("Laboratorium : 0 *");

        jLabel36.setText("Ruang Kelas : 3 *");

        jLabel37.setText("Perpustakaan : 0 *");

        jLabel38.setText("Sanitasi Siswa : 0 *");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38))
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel43.setText("Copyright . Ver.1.0");

        jLabel17.setText(" Email : smpitmaulanaabbasyiah1920@gmail.com   |   No.Hp : 089628184342");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Panel3Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Panel3Layout.createSequentialGroup()
                                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 305, Short.MAX_VALUE))))
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel43)))
                .addContainerGap())
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        Pane.add(Panel3, "card2");

        javax.swing.GroupLayout PanelDashboardLayout = new javax.swing.GroupLayout(PanelDashboard);
        PanelDashboard.setLayout(PanelDashboardLayout);
        PanelDashboardLayout.setHorizontalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDashboardLayout.setVerticalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDashboardLayout.createSequentialGroup()
                        .addComponent(MenuLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1116, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);

    }//GEN-LAST:event_logoutMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

        showSubMenu(slideMenuForm);
    }//GEN-LAST:event_formMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Siswa.Java (sebuah panel)
        Pane.add(Panel3);
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_dashboardMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseMoved

    private void menuGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuruMouseClicked
        // TODO add your handling code here:   
   
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel) 
        Pane.add(new Guru());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuGuruMouseClicked

    private void menuSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseClicked
        // TODO add your handling code here:

        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Siswa());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuSiswaMouseClicked

    private void menuPelajaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPelajaranMouseClicked
        // TODO add your handling code here
    
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Pelajaran());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuPelajaranMouseClicked

    private void menuAbsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsenMouseClicked
        // TODO add your handling code here:
     
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Absen());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuAbsenMouseClicked

    private void penilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuTransaksi);
    }//GEN-LAST:event_penilaianMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuLaporan);
    }//GEN-LAST:event_laporanMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        form.setBackground(new Color(0,51,102));
        form.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        form.setBackground(hoverButton);
    }//GEN-LAST:event_formMouseExited

    private void penilaianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianMouseEntered
        // TODO add your handling code here:
        penilaian.setBackground(new Color(0,51,102));
        penilaian.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_penilaianMouseEntered

    private void penilaianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianMouseExited
        // TODO add your handling code here:
        penilaian.setBackground(hoverButton);
    }//GEN-LAST:event_penilaianMouseExited

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseEntered
        // TODO add your handling code here:
        laporan.setBackground(new Color(0,51,102));
        laporan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanMouseEntered

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseExited
        // TODO add your handling code here:
        laporan.setBackground(hoverButton);
    }//GEN-LAST:event_laporanMouseExited

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        // TODO add your handling code here:
        dashboard.setBackground(new Color(0,51,102));
        dashboard.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        // TODO add your handling code here:
        dashboard.setBackground(hoverButton);
    }//GEN-LAST:event_dashboardMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(0,51,102));
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void menuGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuruMouseEntered
        // TODO add your handling code here:
        menuGuru.setBackground(new Color(0,102,153));
        menuGuru.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuGuruMouseEntered

    private void menuGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuruMouseExited
        // TODO add your handling code here:
        menuGuru.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuGuruMouseExited

    private void menuSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseEntered
        // TODO add your handling code here:
        menuSiswa.setBackground(new Color(0,102,153));
        menuSiswa.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuSiswaMouseEntered

    private void menuSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseExited
        // TODO add your handling code here:
        menuSiswa.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuSiswaMouseExited

    private void menuPelajaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPelajaranMouseEntered
        // TODO add your handling code here:
        menuPelajaran.setBackground(new Color(0,102,153));
        menuPelajaran.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuPelajaranMouseEntered

    private void menuPelajaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPelajaranMouseExited
        // TODO add your handling code here:
        menuPelajaran.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuPelajaranMouseExited

    private void menuAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsenMouseEntered
        // TODO add your handling code here:
        menuAbsen.setBackground(new Color(0,102,153));
        menuAbsen.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuAbsenMouseEntered

    private void menuAbsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsenMouseExited
        // TODO add your handling code here:
        menuAbsen.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuAbsenMouseExited

    private void menuNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNilaiMouseClicked
        // TODO add your handling code here:
        
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Transaksi.Nilai());
        Pane.repaint();
        Pane.revalidate();
        JOptionPane.showMessageDialog(null, "Pilih Penilaian yang tepat pada Tab Penilaian Semester Tengah / Akhir", "Penilaian", HEIGHT);
        
    }//GEN-LAST:event_menuNilaiMouseClicked

    private void menuNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNilaiMouseEntered
        // TODO add your handling code here:
        menuNilai.setBackground(new Color(0,102,153));
        menuNilai.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuNilaiMouseEntered

    private void menuNilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNilaiMouseExited
        // TODO add your handling code here:
        menuNilai.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuNilaiMouseExited

    private void menuReportGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportGuruMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportGuru.jasper";
            HashMap parameter = new HashMap();
            parameter.put("PATH_IMG","lib/");
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
            JasperExportManager.exportReportToPdf(jasperPrint);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportGuruMouseClicked

    private void menuReportGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportGuruMouseEntered
        // TODO add your handling code here:
        menuReportGuru.setBackground(new Color(0,102,153));
        menuReportGuru.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportGuruMouseEntered

    private void menuReportGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportGuruMouseExited
        // TODO add your handling code here:
        menuReportGuru.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportGuruMouseExited

    private void menuReportSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportSiswaMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportSiswa.jasper";
            HashMap parameter = new HashMap();
            parameter.put("PATH_IMG","lib/");
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
            JasperExportManager.exportReportToPdf(jasperPrint);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportSiswaMouseClicked

    private void menuReportSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportSiswaMouseEntered
       // TODO add your handling code here:
        menuReportSiswa.setBackground(new Color(0,102,153));
        menuReportSiswa.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportSiswaMouseEntered

    private void menuReportSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportSiswaMouseExited
        // TODO add your handling code here:
        menuReportSiswa.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportSiswaMouseExited

    private void menuReportWaliKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportWaliKelasMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportWaliKelas.jasper";
            HashMap parameter = new HashMap();
            parameter.put("PATH_IMG","lib/");
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
            JasperExportManager.exportReportToPdf(jasperPrint);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportWaliKelasMouseClicked

    private void menuReportWaliKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportWaliKelasMouseEntered
        // TODO add your handling code here:
        menuReportWaliKelas.setBackground(new Color(0,102,153));
        menuReportWaliKelas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportWaliKelasMouseEntered

    private void menuReportWaliKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportWaliKelasMouseExited
        // TODO add your handling code here:
        menuReportWaliKelas.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportWaliKelasMouseExited

    
    private void menuReportRaportSiswaTengahSemesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportRaportSiswaTengahSemesterMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, cbPilihNisTengahSm, "Pilih NIS Untuk Nilai Raport", JOptionPane.YES_NO_OPTION);
        if(ok == 0){
            int ok2 = JOptionPane.showConfirmDialog(null, cbPilihSemester, "Pilih SEMESTER Untuk Nilai Raport", JOptionPane.YES_NO_OPTION);
            if(ok2 == 0){
                pilihNis = cbPilihNisTengahSm.getSelectedItem().toString();
                pilihSemester = cbPilihSemester.getSelectedItem().toString();
                try{
                    String namaFile = "src/Laporan/ReportNilaiTengahSemester.jasper";
                    HashMap parameter = new HashMap();
                    parameter.put("PATH_IMG","lib/");
                    parameter.put("NIS_SISWA", pilihNis);
                    parameter.put("SEMESTER_SISWA", pilihSemester);
                    File report_file = new File(namaFile);
                    JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
                    JasperViewer.viewReport(jasperPrint, false);
                    JasperViewer.setDefaultLookAndFeelDecorated(true);
                    //export file
                    JasperExportManager.exportReportToPdf(jasperPrint);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_menuReportRaportSiswaTengahSemesterMouseClicked

    private void menuReportRaportSiswaTengahSemesterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportRaportSiswaTengahSemesterMouseEntered
        // TODO add your handling code here:
        menuReportRaportSiswaTengahSemester.setBackground(new Color(0,102,153));
        menuReportRaportSiswaTengahSemester.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportRaportSiswaTengahSemesterMouseEntered

    private void menuReportRaportSiswaTengahSemesterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportRaportSiswaTengahSemesterMouseExited
        // TODO add your handling code here:
        menuReportRaportSiswaTengahSemester.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportRaportSiswaTengahSemesterMouseExited

    private void menuReportRaportSiswaAkhirSemesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportRaportSiswaAkhirSemesterMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, cbPilihNisAkhirSm, "Pilih NIS Untuk Nilai Raport", JOptionPane.YES_NO_OPTION);
        if(ok == 0){
            int ok2 = JOptionPane.showConfirmDialog(null, cbPilihSemester, "Pilih SEMESTER Untuk Nilai Raport", JOptionPane.YES_NO_OPTION);
            if(ok2 == 0){
                pilihNis = cbPilihNisAkhirSm.getSelectedItem().toString();
                pilihSemester = cbPilihSemester.getSelectedItem().toString();
                keterangan = getKet();
                try{
                    String namaFile = "src/Laporan/ReportNilaiAkhirSemester.jasper";
                    HashMap parameter = new HashMap();
                    parameter.put("PATH_IMG","lib/");
                    parameter.put("NIS_SISWA", pilihNis);
                    parameter.put("SEMESTER_SISWA", pilihSemester);
                    parameter.put("KETERANGAN", keterangan);
                    File report_file = new File(namaFile);
                    JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
                    JasperViewer.viewReport(jasperPrint, false);
                    JasperViewer.setDefaultLookAndFeelDecorated(true);
                    //export file
                    JasperExportManager.exportReportToPdf(jasperPrint);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_menuReportRaportSiswaAkhirSemesterMouseClicked

    private void menuReportRaportSiswaAkhirSemesterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportRaportSiswaAkhirSemesterMouseEntered
        // TODO add your handling code here:
        menuReportRaportSiswaAkhirSemester.setBackground(new Color(0,102,153));
        menuReportRaportSiswaAkhirSemester.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportRaportSiswaAkhirSemesterMouseEntered

    private void menuReportRaportSiswaAkhirSemesterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportRaportSiswaAkhirSemesterMouseExited
        // TODO add your handling code here:
        menuReportRaportSiswaAkhirSemester.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportRaportSiswaAkhirSemesterMouseExited

    private void menuWaliKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWaliKelasMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new WaliKelas());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuWaliKelasMouseClicked

    private void menuWaliKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWaliKelasMouseEntered
        // TODO add your handling code here:
        menuWaliKelas.setBackground(new Color(0,102,153));
        menuWaliKelas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuWaliKelasMouseEntered

    private void menuWaliKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWaliKelasMouseExited
        // TODO add your handling code here:
        menuWaliKelas.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuWaliKelasMouseExited
    protected void getRelasiNisTengahSm(){
     
        String sql = "SELECT DISTINCT siswa.nis FROM siswa INNER join nilai_tengah_semester On siswa.nis = nilai_tengah_semester.nis;";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){ 
                String a = hasil.getString("siswa.nis");
                
                String[] data={a};
                cbPilihNisTengahSm.addItem(a);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    protected void getRelasiNisAkhirSm(){
     
        String sql = "SELECT DISTINCT siswa.nis FROM siswa INNER join nilai_akhir_semester On siswa.nis = nilai_akhir_semester.nis;";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){ 
                String a = hasil.getString("siswa.nis");
                
                String[] data={a};
                cbPilihNisAkhirSm.addItem(a);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
     protected double getRataRata(){ 
        double akhir = 0; 
        String sql = "SELECT (SUM(AVG_nilai_tengah + AVG_nilai_pengetahuan_akhir + AVG_nilai_keterampilan_akhir)/SUM(count)) AS AVG_kesuluruhan \n" +
        "FROM (\n" +
        "	SELECT \n" +
        "	   AVG(nilai_tengah_semester.nilai) AS AVG_nilai_tengah, \n" +
        "	   AVG(nilai_akhir_semester.nilai_pengetahuan) AS AVG_nilai_pengetahuan_akhir, \n" +
        "	   AVG(nilai_akhir_semester.nilai_keterampilan) AS AVG_nilai_keterampilan_akhir,\n" +
        "	   3 AS count\n" +
        "	FROM siswa\n" +
        "	   INNER JOIN nilai_akhir_semester ON siswa.nis = nilai_akhir_semester.nis\n" +
        "	   INNER JOIN nilai_tengah_semester ON nilai_tengah_semester.nis = siswa.nis\n" +
        "       WHERE siswa.nis='"+pilihNis+"' AND nilai_akhir_semester.semester='"+pilihSemester+"'\n"+        
        ") AS AVGS;";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                akhir = hasil.getDouble("AVG_kesuluruhan");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
            
            return akhir;
    }
    
    protected String getKet(){
        double hitung = getRataRata();
        String Ket = "";
        
        if((hitung >= 70) && (hitung <= 100)){
            Ket = "LULUS";
        }else if ((hitung >= 0)&&(hitung < 70)){
            Ket = "TIDAK LULUS";
        }
        return Ket;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuLogo;
    private javax.swing.JPanel Pane;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JComboBox<String> cbPilihNisAkhirSm;
    private javax.swing.JComboBox<String> cbPilihNisTengahSm;
    private javax.swing.JComboBox<String> cbPilihSemester;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menuAbsen;
    private javax.swing.JLabel menuGuru;
    private javax.swing.JLabel menuNilai;
    private javax.swing.JLabel menuPelajaran;
    private javax.swing.JLabel menuReportGuru;
    private javax.swing.JLabel menuReportRaportSiswaAkhirSemester;
    private javax.swing.JLabel menuReportRaportSiswaTengahSemester;
    private javax.swing.JLabel menuReportSiswa;
    private javax.swing.JLabel menuReportWaliKelas;
    private javax.swing.JLabel menuSiswa;
    private javax.swing.JLabel menuWaliKelas;
    private javax.swing.JLabel penilaian;
    private javax.swing.JPanel slideMenuForm;
    private javax.swing.JPanel slideMenuLaporan;
    private javax.swing.JPanel slideMenuTransaksi;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
