/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Naufal Sholahuddin
 */
public class Pelajaran extends javax.swing.JPanel {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
       
    
    protected void kosong(){
        tKdMapel.setText("");
        tMapel.setText("");
        CbMuatan.setSelectedIndex(0);
        tKkm.setText("");
    }
    
    protected void datatable(){
        Object[] Baris = {
            "Kode Pelajaran",
            "Mata Pelajaran",
            "Muatan Lokal/Bukan",
            "KKM"
        };
        tabmode = new DefaultTableModel(null, Baris);
        tablePelajaran.setModel(tabmode);

        String sql = "SELECT * FROM pelajaran";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kd_mapel");
                String b = hasil.getString("mapel");
                String c = hasil.getString("jenis");
                String d = hasil.getString("kkm");
                
                String[] data={a, b, c, d};
                tabmode.addRow(data);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    /** Creates new form Pelajaran */
    public Pelajaran() {
        initComponents();
        datatable();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJenisKel = new javax.swing.ButtonGroup();
        Judul1 = new javax.swing.JLabel();
        Input1 = new javax.swing.JPanel();
        tKdMapel = new javax.swing.JTextField();
        tMapel = new javax.swing.JTextField();
        mataPel = new javax.swing.JLabel();
        namaGuru = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        CbMuatan = new javax.swing.JComboBox<>();
        jenis = new javax.swing.JLabel();
        kkm = new javax.swing.JLabel();
        tKkm = new javax.swing.JTextField();
        Tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelajaran = new javax.swing.JTable();
        bCari = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 204));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));

        Judul1.setBackground(new java.awt.Color(255, 255, 255));
        Judul1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul1.setText("FORM MATA PELAJARAN");
        Judul1.setOpaque(true);

        Input1.setBackground(new java.awt.Color(255, 255, 255));

        mataPel.setText("Mata Pelajaran");

        namaGuru.setText("Kode Pelajaran");

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        CbMuatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih -", "Bukan Muatan Lokal", "Muatan Lokal", " " }));

        jenis.setText("Muatan Lokal/Bukan");

        kkm.setText("KKM");

        javax.swing.GroupLayout Input1Layout = new javax.swing.GroupLayout(Input1);
        Input1.setLayout(Input1Layout);
        Input1Layout.setHorizontalGroup(
            Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Input1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Input1Layout.createSequentialGroup()
                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Input1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mataPel)
                                .addComponent(namaGuru))
                            .addComponent(jenis)
                            .addComponent(kkm))
                        .addGap(41, 41, 41)
                        .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tKkm, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tKdMapel, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                .addComponent(tMapel, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                .addComponent(CbMuatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        Input1Layout.setVerticalGroup(
            Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Input1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tKdMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaGuru))
                .addGap(18, 18, 18)
                .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mataPel)
                    .addComponent(tMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbMuatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tKkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kkm))
                .addGap(42, 42, 42)
                .addGroup(Input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClear)
                    .addComponent(bEdit)
                    .addComponent(bHapus)
                    .addComponent(bSimpan))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Tabel.setBackground(new java.awt.Color(255, 255, 255));
        Tabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tablePelajaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Pelajaran", "Mata Pelajaran", "Muatan Lokal/Bukan", "KKM"
            }
        ));
        tablePelajaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelajaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePelajaran);

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabelLayout = new javax.swing.GroupLayout(Tabel);
        Tabel.setLayout(TabelLayout);
        TabelLayout.setHorizontalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(TabelLayout.createSequentialGroup()
                        .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tCari)))
                .addContainerGap())
        );
        TabelLayout.setVerticalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Judul1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Input1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO pelajaran VALUES (?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, tKdMapel.getText());
            stat.setString(2, tMapel.getText());
            stat.setString(3, CbMuatan.getSelectedItem().toString());
            stat.setString(4, tKkm.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA Berhasil Disimpan");
            kosong();
            tKdMapel.requestFocus();
            datatable();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM pelajaran WHERE kd_mapel='"+tKdMapel.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil diUbah ");
                kosong();
                tKdMapel.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal DiUbah " + e);
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE pelajaran set mapel=?, jenis=?, kkm=? WHERE kd_mapel=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, tMapel.getText());
            stat.setString(2, CbMuatan.getSelectedItem().toString());
            stat.setString(3, tKkm.getText());
            stat.setString(4, tKdMapel.getText());
            

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diUbah ");
            kosong();
            tKdMapel.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal DiUbah " + e);
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
    }//GEN-LAST:event_bClearActionPerformed

    private void tablePelajaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelajaranMouseClicked
        // TODO add your handling code here:
        int bar = tablePelajaran.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        
        
        tKdMapel.setText(a);
        tMapel.setText(b);
        CbMuatan.setSelectedItem(c);
        tKkm.setText(d);
  
    }//GEN-LAST:event_tablePelajaranMouseClicked

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Kode Pelajaran","Mata Pelajaran","Muatan Lokal/Bukan","KKM"};
        tabmode = new DefaultTableModel(null, Baris);
        tablePelajaran.setModel(tabmode);

        String sql = "SELECT * FROM pelajaran WHERE mapel LIKE '%"+bCari.getText()+"%'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kd_mapel");
                String b = hasil.getString("mapel");
                String c = hasil.getString("jenis");
                String d = hasil.getString("kkm");

                String[] data={a, b, c, d};
                tabmode.addRow(data);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        kosong();
    }//GEN-LAST:event_bCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbMuatan;
    private javax.swing.JPanel Input1;
    private javax.swing.JLabel Judul1;
    private javax.swing.JPanel Tabel;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.ButtonGroup bgJenisKel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel kkm;
    private javax.swing.JLabel mataPel;
    private javax.swing.JLabel namaGuru;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tKdMapel;
    private javax.swing.JTextField tKkm;
    private javax.swing.JTextField tMapel;
    private javax.swing.JTable tablePelajaran;
    // End of variables declaration//GEN-END:variables

}
