/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Form.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author Naufal Sholahuddin
 */
public class Siswa extends javax.swing.JPanel {

    /**
     * Creates new form Siswa
     */
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
       
    
    protected void kosong(){
        tNis.setText("");
        tNamaSiswa.setText("");
        cbRelasiKelas.setSelectedIndex(0);
        tAgama.setText("");
        rbLaki.setSelected(false); 
        rbPerempuan.setSelected(false);
        bgJenisKel.clearSelection();
        tTglLahir.setText("");
        tTmpLahir.setText("");
        tNamaWali.setText("");
        rbLakiWali.setSelected(false); 
        rbPerempuanWali.setSelected(false);
        bgJenisKelWali.clearSelection();
        tNoTelpWali.setText("");
        tAlamatWali.setText("");
        tCari.setText("");
    }
    
    protected void datatable(){
        Object[] Baris = {
            "NIS",
            "Nama",
            "Tempat Lahir",
            "Tanggal Lahir",
            "Kelas",
            "Agama",
            "Jenis Kelamin",
            "Nama Wali",
            "Jenis Kelamin Wali",
            "No. Telp Wali",
            "Alamat Wali"
        };
        tabmode = new DefaultTableModel(null, Baris);
        tableSiswa.setModel(tabmode);

        String sql = "SELECT * FROM siswa";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nis");
                String b = hasil.getString("nama");
                String c = hasil.getString("tmp_lahir");
                String d = hasil.getString("tgl_lahir");
                String e = hasil.getString("kelas");
                String f = hasil.getString("agama");
                String g = hasil.getString("jenis_kel");
                String h = hasil.getString("nama_wali");
                String i = hasil.getString("jenis_kel_wali");
                String j = hasil.getString("no_telp_wali");
                String k = hasil.getString("alamat_wali");
                
                String[] data={a, b, c, d, e, f, g, h, i, j, k};
                tabmode.addRow(data);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public Siswa() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJenisKel = new javax.swing.ButtonGroup();
        bgJenisKelWali = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Input = new javax.swing.JPanel();
        DataSiswa = new javax.swing.JPanel();
        nis = new javax.swing.JLabel();
        tNis = new javax.swing.JTextField();
        namaSiswa = new javax.swing.JLabel();
        tNamaSiswa = new javax.swing.JTextField();
        kelas = new javax.swing.JLabel();
        cbRelasiKelas = new javax.swing.JComboBox<>();
        jenisKelamin = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        tmpLahir = new javax.swing.JLabel();
        tTmpLahir = new javax.swing.JTextField();
        tglLahir = new javax.swing.JLabel();
        tTglLahir = new javax.swing.JTextField();
        agama = new javax.swing.JLabel();
        tAgama = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        DataWali = new javax.swing.JPanel();
        namaWali = new javax.swing.JLabel();
        jenisKelWali = new javax.swing.JLabel();
        noTelpWali = new javax.swing.JLabel();
        alamatWali = new javax.swing.JLabel();
        tNamaWali = new javax.swing.JTextField();
        tNoTelpWali = new javax.swing.JTextField();
        jScrollPaneWali = new javax.swing.JScrollPane();
        tAlamatWali = new javax.swing.JTextArea();
        rbPerempuanWali = new javax.swing.JRadioButton();
        rbLakiWali = new javax.swing.JRadioButton();
        Tabel = new javax.swing.JPanel();
        tCari = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM SISWA");
        jLabel1.setOpaque(true);

        Input.setBackground(new java.awt.Color(255, 255, 255));

        DataSiswa.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Siswa"));

        nis.setText("NIS");

        namaSiswa.setText("Nama Siswa");

        kelas.setText("Kelas");

        cbRelasiKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9" }));

        jenisKelamin.setText("Jenis Kelamin");

        bgJenisKel.add(rbLaki);
        rbLaki.setText("Laki-Laki");

        bgJenisKel.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        tmpLahir.setText("Tempat Lahir");

        tglLahir.setText("Tanggal Lahir");

        agama.setText("Agama");

        javax.swing.GroupLayout DataSiswaLayout = new javax.swing.GroupLayout(DataSiswa);
        DataSiswa.setLayout(DataSiswaLayout);
        DataSiswaLayout.setHorizontalGroup(
            DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataSiswaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaSiswa)
                    .addComponent(kelas)
                    .addComponent(jenisKelamin)
                    .addComponent(tmpLahir)
                    .addComponent(tglLahir)
                    .addComponent(agama)
                    .addComponent(nis))
                .addGap(21, 21, 21)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNis, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(DataSiswaLayout.createSequentialGroup()
                            .addComponent(rbLaki)
                            .addGap(18, 18, 18)
                            .addComponent(rbPerempuan))
                        .addComponent(cbRelasiKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tTglLahir)
                        .addComponent(tTmpLahir)
                        .addComponent(tNamaSiswa)
                        .addComponent(tAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        DataSiswaLayout.setVerticalGroup(
            DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataSiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nis))
                .addGap(18, 18, 18)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaSiswa)
                    .addComponent(tNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelas)
                    .addComponent(cbRelasiKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKelamin)
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan))
                .addGap(18, 18, 18)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmpLahir)
                    .addComponent(tTmpLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglLahir)
                    .addComponent(tTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agama)
                    .addComponent(tAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        DataWali.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Wali"));

        namaWali.setText("Nama Wali");

        jenisKelWali.setText("Jenis Kelamin");

        noTelpWali.setText("No. Telpon");

        alamatWali.setText("Alamat");

        tAlamatWali.setColumns(20);
        tAlamatWali.setRows(5);
        jScrollPaneWali.setViewportView(tAlamatWali);

        bgJenisKelWali.add(rbPerempuanWali);
        rbPerempuanWali.setText("Perempuan");

        bgJenisKelWali.add(rbLakiWali);
        rbLakiWali.setText("Laki-Laki");

        javax.swing.GroupLayout DataWaliLayout = new javax.swing.GroupLayout(DataWali);
        DataWali.setLayout(DataWaliLayout);
        DataWaliLayout.setHorizontalGroup(
            DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataWaliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisKelWali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNamaWali, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DataWaliLayout.createSequentialGroup()
                        .addComponent(rbLakiWali)
                        .addGap(18, 18, 18)
                        .addComponent(rbPerempuanWali)))
                .addGap(58, 58, 58))
            .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DataWaliLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(namaWali, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DataWaliLayout.createSequentialGroup()
                            .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DataWaliLayout.createSequentialGroup()
                                    .addComponent(noTelpWali)
                                    .addGap(60, 60, 60))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataWaliLayout.createSequentialGroup()
                                    .addComponent(alamatWali)
                                    .addGap(79, 79, 79)))
                            .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tNoTelpWali, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPaneWali, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        DataWaliLayout.setVerticalGroup(
            DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataWaliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tNamaWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLakiWali)
                    .addComponent(rbPerempuanWali)
                    .addComponent(jenisKelWali))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DataWaliLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(namaWali)
                    .addGap(55, 55, 55)
                    .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(noTelpWali)
                        .addComponent(tNoTelpWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(19, 19, 19)
                    .addGroup(DataWaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(DataWaliLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(alamatWali)))
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout InputLayout = new javax.swing.GroupLayout(Input);
        Input.setLayout(InputLayout);
        InputLayout.setHorizontalGroup(
            InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InputLayout.createSequentialGroup()
                        .addComponent(bSimpan)
                        .addGap(52, 52, 52)
                        .addComponent(bHapus)))
                .addGap(46, 46, 46)
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InputLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bEdit)
                        .addGap(43, 43, 43)
                        .addComponent(bClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputLayout.setVerticalGroup(
            InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DataSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataWali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClear)
                    .addComponent(bEdit)
                    .addComponent(bHapus)
                    .addComponent(bSimpan))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Tabel.setBackground(new java.awt.Color(255, 255, 255));
        Tabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tempat Lahir", "Tanggal Lahir", "Kelas", "Agama", "Jenis Kelamin", "Nama Wali", "Jenis Kelamin Wali", "No. Telp Wali", "Alamat Wali"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSiswa);

        javax.swing.GroupLayout TabelLayout = new javax.swing.GroupLayout(Tabel);
        Tabel.setLayout(TabelLayout);
        TabelLayout.setHorizontalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(TabelLayout.createSequentialGroup()
                        .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TabelLayout.setVerticalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {
            "Nis",
            "Nama",
            "Tempat Lahir",
            "Tanggal Lahir",
            "Kelas",
            "Agama",
            "Jenis Kelamin",
            "Nama Wali",
            "Jenis Kelamin Wali",
            "No. Telp Wali",
            "Alamat Wali"
        };
        tabmode = new DefaultTableModel(null, Baris);
        tableSiswa.setModel(tabmode);

        String sql = "SELECT * FROM siswa WHERE nama LIKE '%"+bCari.getText()+"%'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nis");
                String b = hasil.getString("nama");
                String c = hasil.getString("tmp_lahir");
                String d = hasil.getString("tgl_lahir");
                String e = hasil.getString("kelas");
                String f = hasil.getString("agama");
                String g = hasil.getString("jenis_kel");
                String h = hasil.getString("nama_wali");
                String i = hasil.getString("jenis_kel_wali");
                String j = hasil.getString("no_telp_wali");
                String k = hasil.getString("alamat_wali");

                String[] data={a, b, c, d, e, f, g, h, i, j, k};
                tabmode.addRow(data);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        kosong();
    }//GEN-LAST:event_bCariActionPerformed

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        // TODO add your handling code here:
        int bar = tableSiswa.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        String k = tabmode.getValueAt(bar, 10).toString();

        tNis.setText(a);
        tNamaSiswa.setText(b);
        tTmpLahir.setText(c);
        tTglLahir.setText(d);
        cbRelasiKelas.setSelectedItem(e);
        tAgama.setText(f);

        if(g.equals("Laki-Laki")){
            rbLaki.setSelected(true);
            rbPerempuan.setSelected(false);
        }else{
            rbLaki.setSelected(false);
            rbPerempuan.setSelected(true);
        }
        
        tNamaWali.setText(h);
        
        if(i.equals("Laki-Laki")){
            rbLakiWali.setSelected(true);
            rbPerempuanWali.setSelected(false);
        }else{
            rbLakiWali.setSelected(false);
            rbPerempuanWali.setSelected(true);
        }
        
        tNoTelpWali.setText(j);
        tAlamatWali.setText(k);
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO siswa VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, tNis.getText());
            stat.setString(2, tNamaSiswa.getText());
            stat.setString(3, tTmpLahir.getText());
            stat.setString(4, tTglLahir.getText());
            stat.setString(5, cbRelasiKelas.getSelectedItem().toString());
            stat.setString(6, tAgama.getText());

            String jkel = "";
            if(rbLaki.isSelected()){
                jkel="Laki-Laki";
            }else{
                jkel="Perempuan";
            }

            stat.setString(7, jkel);
            stat.setString(8, tNamaWali.getText());
            
            String jkelWali = "";
            if(rbLakiWali.isSelected()){
                jkelWali="Laki-Laki";
            }else{
                jkelWali="Perempuan";
            }
            
            stat.setString(9, jkelWali);
            stat.setString(10, tNoTelpWali.getText());
            stat.setString(11, tAlamatWali.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA Berhasil Disimpan");
            kosong();
            tNis.requestFocus();
            datatable();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM siswa WHERE nis='"+tNis.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil diUbah ");
                kosong();
                tNis.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal DiUbah " + e);
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE siswa set nama=?, tmp_lahir=?, tgl_lahir=?, kelas=?, agama=?,  jenis_kel=?, nama_wali=?, jenis_kel_wali=?, no_telp_wali=?, alamat_wali=? WHERE nis=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tNamaSiswa.getText());
            stat.setString(2, tTmpLahir.getText());
            stat.setString(3, tTglLahir.getText());
            stat.setString(4, cbRelasiKelas.getSelectedItem().toString());
            stat.setString(5, tAgama.getText());

            String jkel = "";
            if(rbLaki.isSelected()){
                jkel="Laki-Laki";
            }else{
                jkel="Perempuan";
            }

            stat.setString(6, jkel);
            stat.setString(7, tNamaWali.getText());
            
            String jkelWali = "";
            if(rbLakiWali.isSelected()){
                jkelWali="Laki-Laki";
            }else{
                jkelWali="Perempuan";
            }
            
            stat.setString(8, jkelWali);
            stat.setString(9, tNoTelpWali.getText());
            stat.setString(10, tAlamatWali.getText());
            stat.setString(11, tNis.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diUbah ");
            kosong();
            tNis.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal DiUbah " + e);
        }
    }//GEN-LAST:event_bEditActionPerformed

        
    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
    }//GEN-LAST:event_bClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataSiswa;
    private javax.swing.JPanel DataWali;
    private javax.swing.JPanel Input;
    private javax.swing.JPanel Tabel;
    private javax.swing.JLabel agama;
    private javax.swing.JLabel alamatWali;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.ButtonGroup bgJenisKel;
    private javax.swing.ButtonGroup bgJenisKelWali;
    private javax.swing.JComboBox<String> cbRelasiKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneWali;
    private javax.swing.JLabel jenisKelWali;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JLabel kelas;
    private javax.swing.JLabel namaSiswa;
    private javax.swing.JLabel namaWali;
    private javax.swing.JLabel nis;
    private javax.swing.JLabel noTelpWali;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbLakiWali;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JRadioButton rbPerempuanWali;
    private javax.swing.JTextField tAgama;
    private javax.swing.JTextArea tAlamatWali;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tNamaSiswa;
    private javax.swing.JTextField tNamaWali;
    private javax.swing.JTextField tNis;
    private javax.swing.JTextField tNoTelpWali;
    private javax.swing.JTextField tTglLahir;
    private javax.swing.JTextField tTmpLahir;
    private javax.swing.JTable tableSiswa;
    private javax.swing.JLabel tglLahir;
    private javax.swing.JLabel tmpLahir;
    // End of variables declaration//GEN-END:variables
}
